#!/bin/sh
## Darch system update: pull the newest image, build recipe, upload to stage

## Configuration
BASE_IMAGE="pniedzwiedzinski/arch-ltd" # Your os image / recipe base
RECIPE="larbs-pn"
RECIPE_LOCATION="/home/pn/code/darch-recipes/personal-recipes"

set -eu pipefail

if [ "$UID" != "0" ]; then
	printf "You should run this as root\n"
	exit 1
fi

set -x

darch images pull $BASE_IMAGE

if [ -n $RECIPE ]; then
	cd $RECIPE_LOCATION
	darch recipes build $RECIPE
	BOOT_IMAGE="$RECIPE"
else
	BOOT_IMAGE="$BASE_IMAGE"
fi

darch stage remove $BOOT_IMAGE:prev || true
darch stage tag $BOOT_IMAGE $BOOT_IMAGE:prev || true
darch stage upload $BOOT_IMAGE --force
