name: Docker Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      SCOPE: pniedzwiedzinski

    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: ./build
      
    - name: Push images
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: ./push
